// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['app']['App']['Connect']();
}

export function ConnectService() {
  return window['go']['app']['App']['ConnectService']();
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function ImportSignatures(arg1) {
  return window['go']['app']['App']['ImportSignatures'](arg1);
}

export function Init(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['Init'](arg1, arg2, arg3, arg4, arg5);
}

export function LogTail(arg1) {
  return window['go']['app']['App']['LogTail'](arg1);
}

export function QuarantineDelete(arg1) {
  return window['go']['app']['App']['QuarantineDelete'](arg1);
}

export function QuarantineList() {
  return window['go']['app']['App']['QuarantineList']();
}

export function QuarantineRestore(arg1) {
  return window['go']['app']['App']['QuarantineRestore'](arg1);
}

export function ReloadSignatures() {
  return window['go']['app']['App']['ReloadSignatures']();
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function ScanCancel(arg1) {
  return window['go']['app']['App']['ScanCancel'](arg1);
}

export function ScanNow(arg1) {
  return window['go']['app']['App']['ScanNow'](arg1);
}

export function ScanSmart() {
  return window['go']['app']['App']['ScanSmart']();
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function ToggleRealTime(arg1) {
  return window['go']['app']['App']['ToggleRealTime'](arg1);
}

export function VerdictAction(arg1, arg2, arg3) {
  return window['go']['app']['App']['VerdictAction'](arg1, arg2, arg3);
}

export function WinClose() {
  return window['go']['app']['App']['WinClose']();
}

export function WinMaximize() {
  return window['go']['app']['App']['WinMaximize']();
}

export function WinMinimize() {
  return window['go']['app']['App']['WinMinimize']();
}

export function WscRegister(arg1) {
  return window['go']['app']['App']['WscRegister'](arg1);
}
