// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';
import {events} from '../models';

export function Connect():Promise<void>;

export function ConnectService():Promise<void>;

export function Disconnect():Promise<void>;

export function GetSettings():Promise<config.Config>;

export function ImportSignatures(arg1:string):Promise<void>;

export function Init(arg1:context.Context,arg2:any,arg3:any,arg4:any,arg5:any):Promise<void>;

export function LogTail(arg1:number):Promise<Array<string>>;

export function PickFile():Promise<string>;

export function PickFolder():Promise<string>;

export function QuarantineDelete(arg1:string):Promise<void>;

export function QuarantineList():Promise<Array<Record<string, any>>>;

export function QuarantineRestore(arg1:string):Promise<void>;

export function ReloadSignatures():Promise<void>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function ScanCancel(arg1:string):Promise<void>;

export function ScanNow(arg1:Array<string>):Promise<void>;

export function ScanSmart():Promise<void>;

export function Status():Promise<events.Status>;

export function ToggleRealTime(arg1:boolean):Promise<void>;

export function VerdictAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WinClose():Promise<void>;

export function WinMaximize():Promise<void>;

export function WinMinimize():Promise<void>;

export function WscRegister(arg1:boolean):Promise<void>;
